package se.chimps.js.vdom.attributes

import org.scalajs.dom.raw.{Event, FocusEvent, MouseEvent}
import se.chimps.js.vdom.util.{ListenerBuilder, PropertyBuilder}

object Attributes {
	def href = PropertyBuilder("href")
	def src = PropertyBuilder("src")
	def `type` = PropertyBuilder("type")
	def tpe = PropertyBuilder("type")
	def id = PropertyBuilder("id")
	def `class` = PropertyBuilder("class")
	def cls = PropertyBuilder("class")
	def name = PropertyBuilder("name")
	def value = PropertyBuilder("value")
	def title = PropertyBuilder("title")
	def method = PropertyBuilder("method")
	def action = PropertyBuilder("action")
	def placeholder = PropertyBuilder("placeholder")
	def `for` = PropertyBuilder("for")
	def alt = PropertyBuilder("alt")
	def rel = PropertyBuilder("rel")
	def rows = PropertyBuilder("rows")
	def cols = PropertyBuilder("cols")
	def selected = PropertyBuilder("selected")
	def checked = PropertyBuilder("checked")
	def contenteditable = PropertyBuilder("contenteditable")
	def colspan = PropertyBuilder("colspan")
	def rowspan = PropertyBuilder("rowspan")
	def meta = PropertyBuilder("meta")
	def min = PropertyBuilder("min")
	def max = PropertyBuilder("max")
	def multiple = PropertyBuilder("multiple")
	def pattern = PropertyBuilder("pattern")
	def required = PropertyBuilder("required")
	def step = PropertyBuilder("step")
	def target = PropertyBuilder("target")
	def slot = PropertyBuilder("slot")
	def click = ListenerBuilder[MouseEvent]("click")
	def input = ListenerBuilder[Event]("input")
	def blur = ListenerBuilder[FocusEvent]("blur")
	def change = ListenerBuilder[Event]("change")
}
